apiVersion: batch/v1
kind: CronJob
metadata:
  name: bike-rental-inference-generator
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: test-mlflow-container
            image: quay.io/rhoai-edge/ab-jq@sha256:492b950bef86a0c33163ccc53e96a9ec8847773ad3fecbf1e5c92be932866e04
            securityContext:
              allowPrivilegeEscalation: false
              runAsNonRoot: true
              seccompProfile:
                type: "RuntimeDefault"
              capabilities:
                drop:
                - ALL
            command:
            - /bin/bash
            - -c
            - |
              echo "Test inference REST web service"
              echo "Data:"
              cat /workspace/test-data/test-data.json
              # Add your expected response here or remove this line if not needed
              INDEX=$(( RANDOM % 20 ))
              
              # Number of requests between 100 and 1000
              R_COUNT=$(( RANDOM % 91 + 10 ))
              # Number of concurrent requests between 100 and R_COUNT
              R_RATE=$(( RANDOM % ($R_COUNT - 9) + 10 ))

              # Randomly selects a record from data.json
              RANDOM_ROW=$(cat /workspace/test-data/test-data.json | jq -r ".dataframe_split.data | .[$INDEX]")
              PAYLOAD="{\"dataframe_split\": {\"columns\":[ \"day\", \"mnth\", \"year\", \"season\",\"holiday\", \"weekday\", \"workingday\", \"weathersit\", \"temp\", \"hum\", \"windspeed\" ], \"data\":[$RANDOM_ROW]}}"
              echo "Payload: $PAYLOAD"
              echo "$PAYLOAD" > /tmp/payload.json


              # Call the service
              SRVC_URL="http://$(MODEL_NAME)-$(MODEL_VERSION):8080/$(TEST_ENDPOINT)"
              echo ""
              echo "Call inference service $SRVC_URL :"
              echo "Number of requests: ${R_COUNT} concurrent requests: ${R_RATE}"
              echo ""
              # Use ab for load testing with 100 concurrent requests
              ab -s 300 -p /tmp/payload.json -T "application/json" -c $R_RATE -n $R_COUNT $SRVC_URL
            env:
            - name: MODEL_NAME
              value: "bike-rental-app-model"  # modify this
            - name: MODEL_VERSION
              value: "1"  # modify this if needed
            - name: TEST_ENDPOINT
              value: "invocations"  # modify this
            volumeMounts:
            - name: test-data-volume
              mountPath: /workspace/test-data
          volumes:
          - name: test-data-volume
            configMap:
              name: to-be-replaced-by-kustomize
          restartPolicy: OnFailure

