apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - multiclusterobservability.yaml
  - grafana-dashboard-edge-inference-health.yaml

secretGenerator:
- name: thanos-object-storage
  files:
  - secrets/thanos.yaml
  options:
    disableNameSuffixHash: true
