apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: abdalla-test-pr-61
namePrefix: abdalla-ai-edge-

commonAnnotations:
  apps.open-cluster-management.io/git-path: acm/odh-edge/apps/bike-rental-app

replacements:
- source:
    kind: Placement
    group: cluster.open-cluster-management.io
    fieldPath: metadata.name
  targets:
  - select:
      group: apps.open-cluster-management.io
      kind: Subscription
    fieldPaths:
      - spec.placement.placementRef.name

# Can't do this as a "replacement", as needs to be of form namespace/name
patches:
- patch: |-
    - op: replace
      path: /spec/channel
      value: abdalla-ai-edge-channel
  target:
    kind: Subscription
- patch: |-
    - op: replace
      path: /spec/pathname
      value: https://github.com/devguyio/ai-edge
  target:
    kind: Channel
